# Redpanda Configuration
redpanda:
  data_directory: /var/lib/redpanda/data
  rpc_server:
    address: 0.0.0.0
    port: 33145
  kafka_api:
    - address: 0.0.0.0
      port: 9092
      name: internal
      authentication_method: none
    - address: 0.0.0.0
      port: 9223
      name: external
      authentication_method: sasl
  admin:
    - address: 0.0.0.0
      port: 9644
  developer_mode: true
  auto_create_topics_enabled: true
  group_topic_partitions: 3
  storage_min_free_bytes: 10485760
  log_segment_size: 1073741824

# SASL Configuration
kafka_api_tls: []

# Enable SASL authentication
enable_sasl: true
sasl_mechanisms:
  - SCRAM-SHA-256

# SASL users configuration
superusers:
  - admin

# Admin user credentials
admin_api_doc_dir: /usr/share/redpanda/admin-api-doc
