version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ~/docker-services/data/postgres:/var/lib/postgresql/data
      - ./config:/etc/postgresql
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge