version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:9223
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:9223
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:8083
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:8083
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:8084
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=info
    ports:
      - "9223:9223"  # Kafka API (external)
      - "9092:9092"  # Kafka API (internal)
      - "8083:8083"  # Pandaproxy (REST API)
      - "8084:8084"  # Schema Registry
      - "9644:9644"  # Admin API
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    environment:
      - REDPANDA_ENVIRONMENT=development
    networks:
      - redpanda-network
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info"]
      interval: 30s
      timeout: 10s
      retries: 5

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: redpanda:9092
      REDPANDA_ADMIN_API_ENABLED: "true"
      REDPANDA_ADMIN_API_URLS: http://redpanda:9644
    ports:
      - "8080:8080"  # Console Web UI
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - redpanda-network

volumes:
  redpanda-data:
    driver: local

networks:
  redpanda-network:
    driver: bridge
