version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/docker-services/data/minio:/data
      - ./config:/etc/minio
    command: server /data --console-address ":9001"
    networks:
      - minio-network

networks:
  minio-network:
    driver: bridge