version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ~/docker/data/redis:/data
      - ./config:/usr/local/etc/redis
    command: redis-server --appendonly yes
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge